// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCilOEZmeJ6dYvjcldaNqOtf78Q4ZUcaoY',
    appId: '1:47749362977:web:d5574d13425619d62b3a60',
    messagingSenderId: '47749362977',
    projectId: 'authapp1-72314',
    authDomain: 'authapp1-72314.firebaseapp.com',
    storageBucket: 'authapp1-72314.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_EfNfkqvnRHrhEgrqtPtMqaVXH3LiLc8',
    appId: '1:47749362977:android:80dbab4e7470d7672b3a60',
    messagingSenderId: '47749362977',
    projectId: 'authapp1-72314',
    storageBucket: 'authapp1-72314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANL1-r22Oj7pFOZlL3yflFoq2GL7DnN_0',
    appId: '1:47749362977:ios:6abc09940f1bd4b72b3a60',
    messagingSenderId: '47749362977',
    projectId: 'authapp1-72314',
    storageBucket: 'authapp1-72314.appspot.com',
    iosBundleId: 'com.example.authenticiationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANL1-r22Oj7pFOZlL3yflFoq2GL7DnN_0',
    appId: '1:47749362977:ios:6abc09940f1bd4b72b3a60',
    messagingSenderId: '47749362977',
    projectId: 'authapp1-72314',
    storageBucket: 'authapp1-72314.appspot.com',
    iosBundleId: 'com.example.authenticiationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCilOEZmeJ6dYvjcldaNqOtf78Q4ZUcaoY',
    appId: '1:47749362977:web:2544df41837d717e2b3a60',
    messagingSenderId: '47749362977',
    projectId: 'authapp1-72314',
    authDomain: 'authapp1-72314.firebaseapp.com',
    storageBucket: 'authapp1-72314.appspot.com',
  );

}